// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReceptionTracker.Infrastructure.Persistence;

#nullable disable

namespace ReceptionTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReceptionDbContext))]
    partial class ReceptionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ReceptionTracker.Domain.Orders.Carton", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PalletId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PalletId", "Code")
                        .IsUnique();

                    b.ToTable("Cartons", (string)null);
                });

            modelBuilder.Entity("ReceptionTracker.Domain.Orders.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("ReceptionTracker.Domain.Orders.Pallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "Code")
                        .IsUnique();

                    b.ToTable("Pallets", (string)null);
                });

            modelBuilder.Entity("ReceptionTracker.Domain.Orders.ProductLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReceived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CartonId");

                    b.ToTable("ProductLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductLines_ExpectedQuantity_Positive", "\"ExpectedQuantity\" > 0");
                        });
                });

            modelBuilder.Entity("ReceptionTracker.Domain.Orders.Carton", b =>
                {
                    b.HasOne("ReceptionTracker.Domain.Orders.Pallet", null)
                        .WithMany("Cartons")
                        .HasForeignKey("PalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReceptionTracker.Domain.Orders.Pallet", b =>
                {
                    b.HasOne("ReceptionTracker.Domain.Orders.Order", null)
                        .WithMany("Pallets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReceptionTracker.Domain.Orders.ProductLine", b =>
                {
                    b.HasOne("ReceptionTracker.Domain.Orders.Carton", null)
                        .WithMany("Products")
                        .HasForeignKey("CartonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReceptionTracker.Domain.Orders.Carton", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ReceptionTracker.Domain.Orders.Order", b =>
                {
                    b.Navigation("Pallets");
                });

            modelBuilder.Entity("ReceptionTracker.Domain.Orders.Pallet", b =>
                {
                    b.Navigation("Cartons");
                });
#pragma warning restore 612, 618
        }
    }
}
