<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReceptionTracker.Application\ReceptionTracker.Application.csproj" />
  </ItemGroup>

</Project>
